name: wba-run
channels:
  - defaults
dependencies:
  - pip=19.1
  - py-xgboost=0.80
  - python=3.6.2
  - scikit-learn=0.20.3
  - pip:
    - azureml-sdk==1.0.33
    - azureml-train-automl==1.0.33
    - inference-schema==0.1a0
    - numpy==1.16.2
    - pandas==0.24.2
    - Pattern==3.6
